### ISSUE TITLE
Dependencies not downloadable - Artifactory returns 404

### ISSUE THREAD

**Issue by Telacur** [ColyTeam/JDATesting#56]
Hello everyone,

I wanted to upgrade to the latest version but my Maven complained that the version does not exist.

```
Downloading from coly: https://m2.coly.dev/releases/dev/coly/JDATesting/0.7.0/JDATesting-0.7.0.pom
[WARNING] The POM for dev.coly:JDATesting:jar:0.7.0 is missing, no dependency information available
```

Even trying to download our previously used version failed with a 404 error:
`https://m2.coly.dev/releases/dev/coly/JDATesting/0.4.3/JDATesting-0.4.3.pom`

Neither my local machine nor an official standard github runner is able to download it.

Can you please check if the artifactory is running?
Thank you very much for your help!

**Comment by klegul** [comment]
Hey,

sorry my maven repository crashed. I have now restarted it and the files should now download. I will create a health check that will send me a notification in the future. Thanks for letting me know.

**Comment by Telacur** [comment]
Works again!
Thank you for the quick fix and your work in general :-)
